export type Suit = '♠' | '♥' | '♦' | '♣'
export type Rank = 'A' | 'K' | 'Q' | 'J' | '10' | '9' | '8' | '7'
export type Card = { id: string; rank: Rank; suit: Suit; special?: 'WILD' | 'SPY' | 'SHIELD' | 'SWAP' | 'REVERSE' | 'TRUTH' | 'DOUBLE' }
export type Player = { id: string; name: string; avatar: string; hand: Card[]; shield: boolean; status?: string; ai?: boolean }
export type Claim = { playerId: string; rank: Rank; count: number; cards: Card[] }
export type GameState = { players: Player[]; current: number; direction: 1 | -1; deck: Card[]; lastClaim?: Claim; phase: 'select' | 'respond' | 'over'; log: string[]; winner?: string }
const ranks: Rank[] = ['A','K','Q','J','10','9','8','7']; const suits: Suit[] = ['♠','♥','♦','♣']
const specials: Card['special'][] = ['WILD','SPY','SHIELD','SWAP','REVERSE','TRUTH','DOUBLE']
export const claimIsTruthful = (claim: Claim) => claim.cards.every(card => card.special ? card.special === 'WILD' : card.rank === claim.rank)
export const makeDeck = () => [...ranks.flatMap(rank => suits.map(suit => ({ id: `${rank}${suit}`, rank, suit }))), ...specials.map((special, i) => ({ id: `x${i}`, rank: 'A' as Rank, suit: '♠' as Suit, special }))].sort(() => Math.random() - .5)
export function newGame(): GameState { const deck = makeDeck(); const names = [['you','You','✦'],['maya','Maya','✿'],['leo','Leo','◈'],['nova','Nova','✧']] as const; const players = names.map(([id,name,avatar], i) => ({id,name,avatar,hand: deck.splice(0,5),shield:false,ai:i>0})); return {players,current:0,direction:1,deck,phase:'select',log:['The table is set. Trust nobody.']} }
export function play(state: GameState, ids: string[], rank: Rank): GameState { const player=state.players[state.current]; const cards=player.hand.filter(c=>ids.includes(c.id)); if(!cards.length) return state; const players=state.players.map((p,i)=>i===state.current?{...p,hand:p.hand.filter(c=>!ids.includes(c.id))}:p); const claim={playerId:player.id,rank,count:cards.length,cards}; const challenger=(state.current+state.direction+players.length)%players.length; return {...state,players,current:challenger,lastClaim:claim,phase:'respond',log:[`${player.name} placed ${cards.length} card${cards.length>1?'s':''} — claims ${cards.length} ${rank}${cards.length>1?'s':''}.`, ...state.log]} }
export function resolve(state: GameState, called: boolean): GameState { const claim=state.lastClaim!; const truthful=claimIsTruthful(claim); const loserId=called ? (truthful ? state.players[state.current].id : claim.playerId) : ''; let deck=[...state.deck]; let players=state.players.map(p=>({...p,hand:[...p.hand]})); let result='Claim accepted.'; if(called){ const loser=players.find(p=>p.id===loserId)!; const count=loser.shield?1:2; loser.hand.push(...deck.splice(0,count)); loser.shield=false; result=truthful?`${loser.name} challenged truth — penalty: ${count} cards.`:`${loser.name} was caught bluffing — penalty: ${count} cards.` }
 const winner=players.find(p=>p.hand.length===0)?.id; const next=(state.current+state.direction+players.length)%players.length; return {...state,players,deck,lastClaim:undefined,phase:winner?'over':'select',current:next,winner,log:[result,...state.log]} }
